DaycareProject/DaycareProject/Models/Groups.cs
using System;
using System.Collections.Generic;

namespace DaycareProject.Models
{
    public partial class Groups
    {
        public Groups()
        {
            Children = new HashSet<Children>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Children> Children { get; set; }
    }
}

DaycareProject/DaycareProject/Controllers/ParentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Web;
using Microsoft.AspNetCore.Http;
using System.Net.Http;
using System.Net;
using Newtonsoft.Json.Linq;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;

namespace DaycareProject.Models
{    
    public class ParentsController : Controller
    {
        private readonly daycarelggoContext _context;
        /*
        public ParentsController(daycarelggoContext context)
        {
            _context = context;
        }
        */
        IConfiguration _configuration;

        public ParentsController(IConfiguration configuration, daycarelggoContext context)
        {
            _configuration = configuration;
            _context = context;
        }

        // GET: Parents
        public async Task<IActionResult> Index()
        {
            List < Parents > parentList = await _context.Parents.ToListAsync();
            foreach(Parents p in parentList)
            {
                if (p.Photo != null)
                {
                    string imageBase64Data = Convert.ToBase64String(p.Photo);
                    string imageDataURL = string.Format("data:image/jpg;base64,{0}",imageBase64Data);                    
                    ViewData["img" + p.Id] = imageDataURL;
                }
            }
            return View(parentList);            
        }

        // GET: Parents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parents = await _context.Parents
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parents == null)
            {
                return NotFound();
            }

            return View(parents);
        }

        // GET: Parents/Create
        public IActionResult Create()
        {
            //reCaptcha            
            ViewData["ReCaptchaKey"] = _configuration.GetSection("GoogleReCaptcha:key").Value;

            return View();
        }

        // POST: Parents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirsName,LastName,Email,Password,PasswordRepeat,PhoneNo,Street,City,Province,Country,PostalCode,Verified,Token,Gender,Photo")] Parents parents)
        {

            //reCaptcha            
            ViewData["ReCaptchaKey"] = _configuration.GetSection("GoogleReCaptcha:key").Value;

            if (ModelState.IsValid)
            {
                //store the image in byte[] format in DB
                foreach (var file in Request.Form.Files)
                {
                    MemoryStream ms = new MemoryStream();
                    file.CopyTo(ms);
                    parents.Photo = ms.ToArray();
                    ms.Close();
                    ms.Dispose();
                }
                var emailVerification = await _context.Parents.FirstOrDefaultAsync(x => x.Email == parents.Email);
                if (emailVerification != null)
                {
                    ModelState.AddModelError(string.Empty, "The email is registered, try enother one!");
                    return View(parents);
                }

                //recaptcha
                if (!ReCaptchaPassed(
            Request.Form["g-recaptcha-response"], // that's how you get it from the Request object
            _configuration.GetSection("GoogleReCaptcha:secret").Value
            ))
                {
                    ModelState.AddModelError(string.Empty, "You failed the CAPTCHA!!!");
                    return View(parents);
                }
                //
                _context.Add(parents);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Login));
            }
            return View(parents);
        }

        // GET: Parents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parents = await _context.Parents.FindAsync(id);
            if (parents == null)
            {
                return NotFound();
            }
            return View(parents);
        }

        // POST: Parents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirsName,LastName,Email,Password,PhoneNo,Street,City,Province,Country,PostalCode,Verified,Token,Gender,Photo")] Parents parents)
        {
            if (id != parents.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(parents);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParentsExists(parents.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(parents);
        }

        // GET: Parents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parents = await _context.Parents
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parents == null)
            {
                return NotFound();
            }

            return View(parents);
        }

        // POST: Parents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var parents = await _context.Parents.FindAsync(id);
            _context.Parents.Remove(parents);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ParentsExists(int id)
        {
            return _context.Parents.Any(e => e.Id == id);
        }

        // GET: Parents/Login
        public IActionResult Login()
        {
            return View();
        }

        
        [HttpPost]
        public async Task<IActionResult> Login([Bind("Email,Password")] Parents parents)
        {   
                var parent = await _context.Parents.FirstOrDefaultAsync(x => x.Email == parents.Email && x.Password == parents.Password);

                if (parent == null)
                {                    
                    ModelState.AddModelError(string.Empty, "Invalid username or password");                    
                }
                else
                {
                if (parent.Photo != null)
                {
                    string imageBase64Data = Convert.ToBase64String(parent.Photo);
                    string imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);
                    //ViewBag.ImageDataUrl = imageDataURL;  SessionUserPhoto
                    HttpContext.Session.SetString("SessionUserPhoto", imageDataURL); 
                }
                HttpContext.Session.SetString("SessionUserName", parent.FirsName + " " + parent.LastName);
                HttpContext.Session.SetInt32("SessionUserId", parent.Id);                
                return RedirectToAction("Index", "Home");                   
                }
            
            return View(parents);

        }
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("SessionUserName");
            HttpContext.Session.Remove("SessionUserId");
            HttpContext.Session.Remove("SessionUserPhoto");
            return RedirectToAction("Index", "Home");
        }

        //Recaptcha 
        public static bool ReCaptchaPassed(string gRecaptchaResponse, string secret)
        {
            HttpClient httpClient = new HttpClient();
            var res = httpClient.GetAsync($"https://www.google.com/recaptcha/api/siteverify?secret={secret}&response={gRecaptchaResponse}").Result;
            if (res.StatusCode != HttpStatusCode.OK)
            {
                //logger.LogError("Error while sending request to ReCaptcha");
                return false;
            }

            string JSONres = res.Content.ReadAsStringAsync().Result;
            dynamic JSONdata = JObject.Parse(JSONres);
            if (JSONdata.success != "true")
            {
                return false;
            }

            return true;
        }
        

    }
}

DaycareProject/DaycareProject/Controllers/PrintingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DaycareProject.Models;
using Microsoft.AspNetCore.Hosting;
using Syncfusion.HtmlConverter;
using Syncfusion.Pdf;
using System.IO;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Drawing;
using System.Drawing;
// multi lang
using Microsoft.Extensions.Localization;
//------------------------------------------

namespace DaycareProject.Controllers
{
    public class PrintingController : Controller
    {

        private readonly IHostingEnvironment _hostingEnvironment;
        public PrintingController(IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult ExportToPDF()
        {

            //string mvcVersion = typeof(Controller).Assembly.GetName().Version.ToString();

            //Initialize HTML to PDF converter 
            HtmlToPdfConverter htmlConverter = new HtmlToPdfConverter();
            WebKitConverterSettings settings = new WebKitConverterSettings();
            //Set WebKit path
            settings.WebKitPath = Path.Combine(_hostingEnvironment.ContentRootPath, "QtBinariesWindows");
            //Assign WebKit settings to HTML converter
            htmlConverter.ConverterSettings = settings;
            //Convert URL to PDF

            //PdfDocument document = htmlConverter.Convert("https://www.google.com");
            PdfDocument document = htmlConverter.Convert("https://localhost:44389/Parents/Index");



            using (MemoryStream stream = new MemoryStream())
            {
                document.Save(stream);
                stream.Position = 0;
                document.Close(true);


                //return File(stream.ToArray(), System.Net.Mime.MediaTypeNames.Application.Pdf, "Output.pdf");

                //Defining the ContentType for pdf file.
                string contentType = "application/pdf";
                //Define the file name.
                string fileName = "Output.pdf";
                //Creates a FileContentResult object by using the file contents, content type, and file name.
                return File(stream.ToArray(), contentType, fileName);


            }

        }

        public IActionResult CreateContacts()
        {

            //Create a new PDF document
            PdfDocument document = new PdfDocument();
            //Add a page to the document
            PdfPage page = document.Pages.Add();
            //Create PDF graphics for the page
            PdfGraphics graphics = page.Graphics;
            //----------------------------------------------------------------



            //Set the standard font
            PdfFont font = new PdfStandardFont(PdfFontFamily.Helvetica, 22);
            //Draw the text           
            graphics.DrawString("Thank you for your interest in our kindergarten!", font, PdfBrushes.Black, new Syncfusion.Drawing.PointF(40, 20));
            PdfFont font2 = new PdfStandardFont(PdfFontFamily.Helvetica, 18);
            graphics.DrawString("Contact us with any questions or clarifications.", font2, PdfBrushes.Black, new Syncfusion.Drawing.PointF(0, 80));
            graphics.DrawString("Civic / Postal Address:", font2, PdfBrushes.Black, new Syncfusion.Drawing.PointF(0, 120));
            PdfFont font3 = new PdfStandardFont(PdfFontFamily.Helvetica, 14);
            graphics.DrawString("21275 Lakeshore Road", font3, PdfBrushes.Black, new Syncfusion.Drawing.PointF(30, 150));
            graphics.DrawString("Sainte-Anne-de-Bellevue, Québec", font3, PdfBrushes.Black, new Syncfusion.Drawing.PointF(30, 170));
            graphics.DrawString("H9X 3L9 Canada", font3, PdfBrushes.Black, new Syncfusion.Drawing.PointF(30, 190));

            graphics.DrawString("Contact Information:", font2, PdfBrushes.Black, new Syncfusion.Drawing.PointF(0, 230));

            graphics.DrawString("Phone Number: 514 - 123 - 1234", font3, PdfBrushes.Black, new Syncfusion.Drawing.PointF(30, 260));
            graphics.DrawString("Fax Number: 514 - 123 - 4567", font3, PdfBrushes.Black, new Syncfusion.Drawing.PointF(30, 280));
            graphics.DrawString("Email: Daycare@daycare.com", font3, PdfBrushes.Black, new Syncfusion.Drawing.PointF(30, 300));


            //Saving the PDF to the MemoryStream
            MemoryStream stream = new MemoryStream();

            document.Save(stream);

            //Set the position as '0'.
            stream.Position = 0;

            //Download the PDF document in the browser
            FileStreamResult fileStreamResult = new FileStreamResult(stream, "application/pdf");

            fileStreamResult.FileDownloadName = "Sample.pdf";

            return fileStreamResult;

        }

        public IActionResult CurrentWorkload()
        {



            //string mvcVersion = typeof(Controller).Assembly.GetName().Version.ToString();

            //Initialize HTML to PDF converter 
            HtmlToPdfConverter htmlConverter = new HtmlToPdfConverter();
            WebKitConverterSettings settings = new WebKitConverterSettings();
            //Set WebKit path
            settings.WebKitPath = Path.Combine(_hostingEnvironment.ContentRootPath, "QtBinariesWindows");
            //Assign WebKit settings to HTML converter
            htmlConverter.ConverterSettings = settings;
            //Convert URL to PDF

            //PdfDocument document = htmlConverter.Convert("https://www.google.com");
            PdfDocument document = htmlConverter.Convert("https://localhost:44389/Children/reportCurrentWorkload");



            using (MemoryStream stream = new MemoryStream())
            {
                document.Save(stream);
                stream.Position = 0;
                document.Close(false);


                //return File(stream.ToArray(), System.Net.Mime.MediaTypeNames.Application.Pdf, "Output.pdf");

                //Defining the ContentType for pdf file.
                string contentType = "application/pdf";
                //Define the file name.
                string fileName = "Output.pdf";
                //Creates a FileContentResult object by using the file contents, content type, and file name.
                return File(stream.ToArray(), contentType, fileName);


            }

        }

        public IActionResult WaitingList()
        {

            //string mvcVersion = typeof(Controller).Assembly.GetName().Version.ToString();



            //Initialize HTML to PDF converter 
            HtmlToPdfConverter htmlConverter = new HtmlToPdfConverter();
            WebKitConverterSettings settings = new WebKitConverterSettings();
            //Set WebKit path
            settings.WebKitPath = Path.Combine(_hostingEnvironment.ContentRootPath, "QtBinariesWindows");
            //Assign WebKit settings to HTML converter
            htmlConverter.ConverterSettings = settings;
            //Convert URL to PDF       
            PdfDocument document = htmlConverter.Convert("https://localhost:44389/Children/ReportWaitingList");



            using (MemoryStream stream = new MemoryStream())
            {
                document.Save(stream);
                stream.Position = 0;
                document.Close(false);

                //Defining the ContentType for pdf file.
                string contentType = "application/pdf";
                //Define the file name.
                string fileName = "Output.pdf";
                //Creates a FileContentResult object by using the file contents, content type, and file name.
                return File(stream.ToArray(), contentType, fileName);


            }

        }




        public IActionResult Index()
        {
            return View();
        }
    }
}

DaycareProject/DaycareProject/Views/Home/Contact.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer

@{
    ViewData["Title"] = _localizer["Our Contacts"];
    ViewData["btnSaveContacts"] = _localizer["Save Contacts"];
    ViewData["location"] = _localizer["Our location"];

}
<h1>@ViewData["Title"]</h1>


<div class="btn">
    @{Html.BeginForm("CreateContacts", "Printing", FormMethod.Get);
        {
            <div>
                <input type="submit" value=@ViewData["btnSaveContacts"] style="height:27px" />
            </div>
        }
        Html.EndForm();
    }
</div>

<!--
<div class="btn">
    @{Html.BeginForm("ExportToPDF", "Printing", FormMethod.Post);
        {
            <div>
                <input type="submit" value="Export To PDF" style="width:150px;height:27px" />
            </div>
        }
        Html.EndForm();
    }
</div>
-->



<div class="col">

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@ViewData["location"]</h4>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2801.1161791541394!2d-73.94289468469154!3d45.40699674528012!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4cc9385023ef61af%3A0x612d60de15a505be!2sJohn%20Abbott%20College!5e0!3m2!1sen!2sca!4v1576544959635!5m2!1sen!2sca"
                    width="100%" height="500" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
            </iframe>
            <br><br>

            <h6 class="card-title">Civic / Postal Address:</h6>
            <p class="card-text">21 275 Lakeshore Road</p>
            <p class="card-text">Sainte-Anne-de-Bellevue, Québec</p>
            <p class="card-text">H9X 3L9 Canada</p>
            <h6 class="card-title">Contact Information:</h6>
            <p class="card-text">Phone Number: 514-123-1234</p>
            <p class="card-text">Fax Number: 514-123-4567</p>
            <p class="card-text">Email : <a href="mailto:gilfanovola@gmail.com" target="_blank">General Inquiries </a> | <a href="mailto:gilfanovola@gmail.com" target="_blank">Technical support</a></p>

        </div>
    </div>

</div>

DaycareProject/DaycareProject/Views/Home/Groups.cshtml
@{
    ViewData["Title"] = "Group's information";
}



<h1>@ViewData["Title"]</h1>

<div class="container">
    <div class="row">
        <div class="col-sm-6 col-lg-4">
            Group A (< 2 years)
            <img class="d-block img-fluid" src="~/images/close-up-of-girl-writing-256468.jpg" width="1900" height="1080" alt="First slide" />
            <div>
                <br>
                <h5>
                    Group information (pdf):
                </h5>
                <ul>
                    <li>
                        <div class="btn">
                            @{Html.BeginForm("CurrentWorkload", "Printing", FormMethod.Get);
                                {
                                    <div>
                                        <input type="submit" value="Сurrent workload" style="width:150px;height:27px" />
                                    </div>
                                }
                                Html.EndForm();
                            }
                        </div>
                    </li>

                    <li>
                        <div class="btn">
                            @{Html.BeginForm("WaitingList", "Printing", FormMethod.Get);
                                {
                                    <div>
                                        <input type="submit" value="Waiting list" style="width:150px;height:27px" />
                                    </div>
                                }
                                Html.EndForm();
                            }
                        </div>
                    </li>

                    <!--
                    <li>
                        <div class="btn">
                            @{Html.BeginForm("CreateContacts", "Printing", FormMethod.Get);
                                {
                                    <div>
                                        <input type="submit" value="Free Places" style="width:150px;height:27px" />
                                    </div>
                                }
                                Html.EndForm();
                            }
                        </div>
                    </li>
                    -->
                </ul>

            </div>
        </div>

        <div class="col-sm-6 col-lg-4">
            Group B (2 - 3 years)
            <img class="d-block img-fluid" src="~/images/depth-of-field-photography-of-p-l-a-y-wooden-letter-decors-591652.jpg" width="1900" height="1080" alt="Second slide" />
            <div>
                <br>
                <h5>
                    Group information (pdf):
                </h5>
                <ul>
                    <li>
                        <div class="btn">
                            @{Html.BeginForm("CurrentWorkload", "Printing", FormMethod.Get);
                                {
                                    <div>
                                        <input type="submit" value="Сurrent workload" style="width:150px;height:27px" />
                                    </div>
                                }
                                Html.EndForm();
                            }
                        </div>
                    </li>

                    <li>
                        <div class="btn">
                            @{Html.BeginForm("WaitingList", "Printing", FormMethod.Get);
                                {
                                    <div>
                                        <input type="submit" value="Waiting list" style="width:150px;height:27px" />
                                    </div>
                                }
                                Html.EndForm();
                            }
                        </div>
                    </li>

                    <!--
                    <li>
                        <div class="btn">
                            @{Html.BeginForm("CreateContacts", "Printing", FormMethod.Get);
                                {
                                    <div>
                                        <input type="submit" value="Free Places" style="width:150px;height:27px" />
                                    </div>
                                }
                                Html.EndForm();
                            }
                        </div>
                    </li>
                    -->
                </ul>
            </div>
        </div>

        <div class="col-sm-6 col-lg-4">
            Group C (4 - 5 years)
            <img class="d-block img-fluid" src="~/images/painting-and-drawing-tools-set-207665.jpg" width="1900" height="1080" alt="Third slide" />
            <div>
                <br>
                <h5>
                    Group information (pdf):
                </h5>
                <ul>
                    <li>
                        <div class="btn">
                            @{Html.BeginForm("CurrentWorkload", "Printing", FormMethod.Get);
                                {
                                    <div>
                                        <input type="submit" value="Сurrent workload" style="width:150px;height:27px" />
                                    </div>
                                }
                                Html.EndForm();
                            }
                        </div>
                    </li>

                    <li>
                        <div class="btn">
                            @{Html.BeginForm("WaitingList", "Printing", FormMethod.Get);
                                {
                                    <div>
                                        <input type="submit" value="Waiting list" style="width:150px;height:27px" />
                                    </div>
                                }
                                Html.EndForm();
                            }
                        </div>
                    </li>

                    <!--
                    <li>
                        <div class="btn">
                            @{Html.BeginForm("CreateContacts", "Printing", FormMethod.Get);
                                {
                                    <div>
                                        <input type="submit" value="Free Places" style="width:150px;height:27px" />
                                    </div>
                                }
                                Html.EndForm();
                            }
                        </div>
                    </li>
                    -->
                </ul>

            </div>

        </div>
    </div>
</div>

DaycareProject/DaycareProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!--div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</!-div-->

<header>
    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img class="d-block img-fluid" src="~/images/close-up-of-girl-writing-256468.jpg" width="1900" height="1080" alt="First slide" />
                <div class="carousel-caption" role="option">
                    <h2>
                        All information about our groups:
                        <a asp-area="" asp-controller="Home" asp-action="Groups">Our Groups</a>
                    </h2>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="~/images/depth-of-field-photography-of-p-l-a-y-wooden-letter-decors-591652.jpg" width="1900" height="1080" alt="Second slide" />
                <div class="carousel-caption" role="option">
                    <h2>

                        Would you like to enroll in our kindergarten?
                        <a asp-area="" asp-controller="Parents" asp-action="Create">Register</a>
                    </h2>
                </div>

            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="~/images/painting-and-drawing-tools-set-207665.jpg" width="1900" height="1080" alt="Third slide" />
                <div class="carousel-caption" role="option">
                    <h2>

                        Would you like to contact us?
                        <a asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                    </h2>
                </div>

            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</header>