DaycareProject/DaycareProject/Controllers/ParentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Web;
using Microsoft.AspNetCore.Http;
using System.Net.Http;
using System.Net;
using Newtonsoft.Json.Linq;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;

namespace DaycareProject.Models
{    
    public class ParentsController : Controller
    {
        private readonly daycarelggoContext _context;
        /*
        public ParentsController(daycarelggoContext context)
        {
            _context = context;
        }
        */
        IConfiguration _configuration;

        public ParentsController(IConfiguration configuration, daycarelggoContext context)
        {
            _configuration = configuration;
            _context = context;
        }

        // GET: Parents
        public async Task<IActionResult> Index()
        {
            List < Parents > parentList = await _context.Parents.ToListAsync();
            foreach(Parents p in parentList)
            {
                if (p.Photo != null)
                {
                    string imageBase64Data = Convert.ToBase64String(p.Photo);
                    string imageDataURL = string.Format("data:image/jpg;base64,{0}",imageBase64Data);                    
                    ViewData["img" + p.Id] = imageDataURL;
                }
            }
            return View(parentList);            
        }

        // GET: Parents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parents = await _context.Parents
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parents == null)
            {
                return NotFound();
            }

            return View(parents);
        }

        // GET: Parents/Create
        public IActionResult Create()
        {
            //reCaptcha            
            ViewData["ReCaptchaKey"] = _configuration.GetSection("GoogleReCaptcha:key").Value;

            return View();
        }

        // POST: Parents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirsName,LastName,Email,Password,PasswordRepeat,PhoneNo,Street,City,Province,Country,PostalCode,Verified,Token,Gender,Photo")] Parents parents)
        {

            //reCaptcha            
            ViewData["ReCaptchaKey"] = _configuration.GetSection("GoogleReCaptcha:key").Value;

            if (ModelState.IsValid)
            {
                //store the image in byte[] format in DB
                foreach (var file in Request.Form.Files)
                {
                    MemoryStream ms = new MemoryStream();
                    file.CopyTo(ms);
                    parents.Photo = ms.ToArray();
                    ms.Close();
                    ms.Dispose();
                }
                var emailVerification = await _context.Parents.FirstOrDefaultAsync(x => x.Email == parents.Email);
                if (emailVerification != null)
                {
                    ModelState.AddModelError(string.Empty, "The email is registered, try enother one!");
                    return View(parents);
                }

                //recaptcha
                if (!ReCaptchaPassed(
            Request.Form["g-recaptcha-response"], // that's how you get it from the Request object
            _configuration.GetSection("GoogleReCaptcha:secret").Value
            ))
                {
                    ModelState.AddModelError(string.Empty, "You failed the CAPTCHA!!!");
                    return View(parents);
                }
                //
                _context.Add(parents);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Login));
            }
            return View(parents);
        }

        // GET: Parents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parents = await _context.Parents.FindAsync(id);
            if (parents == null)
            {
                return NotFound();
            }
            return View(parents);
        }

        // POST: Parents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirsName,LastName,Email,Password,PhoneNo,Street,City,Province,Country,PostalCode,Verified,Token,Gender,Photo")] Parents parents)
        {
            if (id != parents.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(parents);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParentsExists(parents.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(parents);
        }

        // GET: Parents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parents = await _context.Parents
                .FirstOrDefaultAsync(m => m.Id == id);
            if (parents == null)
            {
                return NotFound();
            }

            return View(parents);
        }

        // POST: Parents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var parents = await _context.Parents.FindAsync(id);
            _context.Parents.Remove(parents);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ParentsExists(int id)
        {
            return _context.Parents.Any(e => e.Id == id);
        }

        // GET: Parents/Login
        public IActionResult Login()
        {
            return View();
        }

        
        [HttpPost]
        public async Task<IActionResult> Login([Bind("Email,Password")] Parents parents)
        {   
                var parent = await _context.Parents.FirstOrDefaultAsync(x => x.Email == parents.Email && x.Password == parents.Password);

                if (parent == null)
                {                    
                    ModelState.AddModelError(string.Empty, "Invalid username or password");                    
                }
                else
                {
                if (parent.Photo != null)
                {
                    string imageBase64Data = Convert.ToBase64String(parent.Photo);
                    string imageDataURL = string.Format("data:image/jpg;base64,{0}", imageBase64Data);
                    //ViewBag.ImageDataUrl = imageDataURL;  SessionUserPhoto
                    HttpContext.Session.SetString("SessionUserPhoto", imageDataURL); 
                }
                HttpContext.Session.SetString("SessionUserName", parent.FirsName + " " + parent.LastName);
                HttpContext.Session.SetInt32("SessionUserId", parent.Id);                
                return RedirectToAction("Index", "Home");                   
                }
            
            return View(parents);

        }
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("SessionUserName");
            HttpContext.Session.Remove("SessionUserId");
            HttpContext.Session.Remove("SessionUserPhoto");
            return RedirectToAction("Index", "Home");
        }

        //Recaptcha 
        public static bool ReCaptchaPassed(string gRecaptchaResponse, string secret)
        {
            HttpClient httpClient = new HttpClient();
            var res = httpClient.GetAsync($"https://www.google.com/recaptcha/api/siteverify?secret={secret}&response={gRecaptchaResponse}").Result;
            if (res.StatusCode != HttpStatusCode.OK)
            {
                //logger.LogError("Error while sending request to ReCaptcha");
                return false;
            }

            string JSONres = res.Content.ReadAsStringAsync().Result;
            dynamic JSONdata = JObject.Parse(JSONres);
            if (JSONdata.success != "true")
            {
                return false;
            }

            return true;
        }
        

    }
}

DaycareProject/DaycareProject/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DaycareProject.Models
{
    public class SubjectsController : Controller
    {
        private readonly daycarelggoContext _context;

        public SubjectsController(daycarelggoContext context)
        {
            _context = context;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            var daycarelggoContext = _context.Subjects.Include(s => s.ParentNavigation);
            return View(await daycarelggoContext.ToListAsync());
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subjects = await _context.Subjects
                .Include(s => s.ParentNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subjects == null)
            {
                return NotFound();
            }

            return View(subjects);
        }

        // GET: Subjects/Create
        public IActionResult Create()
        {
            ViewData["Parent"] = new SelectList(_context.Parents, "Id", "Email");
            return View();
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title")] Subjects subjects)
        {
            if (ModelState.IsValid)
            {
                subjects.CreatedTs = DateTime.Now;
                if (HttpContext.Session.GetInt32("SessionUserId") == null) //TODO Create an autorization checking
                {
                    return NotFound();
                }
                subjects.Parent = (int)HttpContext.Session.GetInt32("SessionUserId");
                _context.Add(subjects);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Parent"] = new SelectList(_context.Parents, "Id", "Email", subjects.Parent);
            return View(subjects);
        }

        // GET: Subjects/ViewAddComments/5
        public async Task<IActionResult> ViewAddComments(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewData["subjectId"] = id;
            List<Comments> commentList = await _context.Comments.Where(c => c.Subject == id).Include(c => c.SubjectNavigation).Include(c => c.ParentNavigation).ToListAsync();
            var subject = await _context.Subjects.Include(c => c.ParentNavigation).FirstOrDefaultAsync(m => m.Id == id);
            ViewBag.Subject = subject;

            return View(commentList);
        }


        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subjects = await _context.Subjects.FindAsync(id);
            if (subjects == null)
            {
                return NotFound();
            }
            ViewData["Parent"] = new SelectList(_context.Parents, "Id", "Email", subjects.Parent);
            return View(subjects);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Parent,Title,CreatedTs")] Subjects subjects)
        {
            if (id != subjects.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subjects);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectsExists(subjects.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Parent"] = new SelectList(_context.Parents, "Id", "Email", subjects.Parent);
            return View(subjects);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subjects = await _context.Subjects
                .Include(s => s.ParentNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subjects == null)
            {
                return NotFound();
            }

            return View(subjects);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subjects = await _context.Subjects.FindAsync(id);
            _context.Subjects.Remove(subjects);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectsExists(int id)
        {
            return _context.Subjects.Any(e => e.Id == id);
        }
    }
}

DaycareProject/DaycareProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer _localizer

@{
    ViewData["account"] = _localizer["Account"];
    ViewData["login"] = _localizer["Login"];
    ViewData["register"] = _localizer["Register"];

    ViewData["home"] = _localizer["Home"];
    ViewData["groups"] = _localizer["Our Groups"];
    ViewData["privacy"] = _localizer["Privacy"];
    //ViewData["register"] = _localizer["Register"];
    ViewData["contact"] = _localizer["Contact Us"];
    ViewData["pie"] = _localizer["Pie Chart"];

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DaycareProject</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- For social media icons (footer) -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-1/css/all.min.css">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Head", required: false)

</head>
<body>
    <header>

        <!-- 1. Top nav -->
        <nav class="navbar navbar-expand-lg  navbar-dark bg-light">
            <div class="container">

                <!--Change the language from here-->
                <div class="col col-2 col-lg-8">
                    <a href="?culture=fr-FR">
                        <img src="/images/fr2.png" id="Francais" style="margin-right :15px " alt="Francais" title="Francais" width="35" height="25" />
                    </a>
                    <a href="?culture=en-US">
                        <img src="/images/en2.png" id="En" style="margin-right :25px " alt="English" title="English" width="35" height="25" />
                    </a>
                    <a href="?culture=RU">
                        RU

                    </a>


                </div>
                <!--div>Hello @Context.Session.GetString("SessionUserName") nice to see you!</div-->
                <!--Account drop down menu-->
                <img src="@Context.Session.GetString("SessionUserPhoto")" style="width : 50px ; height: auto ; border-radius: 50%;" />
                <div class="col col-lg-2">
                    <div class="dropdown">
                        <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @ViewData["account"]
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            @{ if (String.IsNullOrEmpty(Context.Session.GetString("SessionUserName")))
                                {
                                    <div>
                                        <span class="dropdown-item">
                                            <a asp-area="" asp-controller="Parents" asp-action="Login">@ViewData["login"]</a> or
                                            <a asp-area="" asp-controller="Parents" asp-action="Create">@ViewData["register"]</a>
                                        </span>
                                    </div>
                                }
                                else
                                {
                                    <div>
                                        <span class="dropdown-item">
                                            Hello @Context.Session.GetString("SessionUserName")! <a asp-area="" asp-controller="Parents" asp-action="Logout">Logout.</a>
                                        </span>
                                    </div>
                                    <div>
                                        <span class="dropdown-item">
                                            <a asp-area="" asp-controller="Children" asp-action="Create">Register a child</a>
                                        </span>
                                    </div>
                                    <div>
                                        <span class="dropdown-item">
                                            <a asp-area="" asp-controller="Children" asp-action="Index">Children info</a>
                                        </span>
                                    </div>
                                    <div>
                                        <span class="dropdown-item">
                                            <a asp-area="" asp-controller="Subjects" asp-action="Index">Forum</a>
                                        </span>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>

            </div>
        </nav>
        <!-- END Top nav -->

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark fixed-top border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DaycareProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">@ViewData["home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Groups">@ViewData["groups"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">@ViewData["privacy"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Parents" asp-action="Create">@ViewData["register"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">@ViewData["contact"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="PieChart" asp-action="Index">@ViewData["pie"]</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DaycareProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </!footer-->
    <!-- Footer -->
    <footer class="py-5 bg-dark">

        <div class="container">
            <div class="row white-font-large text-center text-white">
                <div class="col-6">
                    <p>Follow us on social media</p>
                </div>
                <div class="col-6 text-white">
                    <p>Contact us</p>
                </div>
            </div>
            <div class="row">
                <div class="col-6 text-center text-white">
                    <i class="fab fa-facebook-square fa-3x"></i>
                    <i class="far fa-envelope fa-3x"></i>
                    <i class="fab fa-twitter-square fa-3x"></i>
                </div>
                <div class="col-6 text-center text-white">
                    <p class="white-font-large">Phone: (514)-123-1234</p>
                </div>
                <div class="container">
                    <p class="m-0 text-center text-white">Copyright &copy; Daycare project 2020</p>
                </div>
                <!-- /.container -->
            </div>
        </div>
    </footer>
    <!-- Bootstrap JavaScript -->
    <!--
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    -->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>